import { HttpClient, HttpErrorResponse } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { catchError, Observable, throwError } from 'rxjs';
import { User } from '../models/user';
import { LoginRequest } from '../models/LoginRequest';

@Injectable({
  providedIn: 'root'
})
export class UserService {
  private pamUrl = 'http://localhost:8081/pam/register';
  private gwUrl = 'http://localhost:8080/gateway';

  constructor(private http: HttpClient) { }

  registerUser(user: User): Observable<User> {
    return this.http.post<User>(this.pamUrl, user);
  }

  login(loginRequest: LoginRequest): Observable<any> {
    return this.http.post(`${this.gwUrl}/login`, loginRequest).pipe(
      catchError(this.handleError)
    );
  }

  private handleError(error: HttpErrorResponse): Observable<never> {
    // TODO: Add proper logging
    console.error('An error occurred:', error);
    let errorMessage: string;
    if (error.error instanceof ErrorEvent) {
      // Error response generated by client-side
      errorMessage = `Error: ${error.error.message}`;
    } else {
      // Error reponse generated by server-side
      errorMessage = `${error.error.message}`;
    }
    return throwError({ status: error.status, statusText: error.error.status, message: errorMessage });
  }
}
